modLoader = "javafml"
loaderVersion = "[36,)"
license = "Code: GPL-3.0 License | Assets: Attribution-NonCommercial 4.0 International"
issueTrackerURL = "https://github.com/IriDark/Valoria/issues"
[[mods]]
modId = "valoria"
version = "${file.jarVersion}"
displayName = "Valoria"
updateJSONURL = "https://raw.githubusercontent.com/IriDark/Valoria/refs/heads/main/update.json"
displayURL = "https://discord.gg/wWdXpwuPmK"
logoFile="valoria_banner.png"
credits = "Calamity Mod (Sounds)"
authors = "IriDark, Sunday, Kerdo, DuUaader"
description = '''
Valoria â€” A large RPG themed project that adds some mobs, blocks, weapons, and a lot of content in "vanilla" texture style
'''
[[dependencies.valoria]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.valoria]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.valoria]]
modId = "curios"
mandatory = true
versionRange = "[5.2.0-beta.3+1.20.1,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.valoria]]
modId = "geckolib"
mandatory = true
versionRange = "1.20.1-4.4.7,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.valoria]]
modId = "tridot"
mandatory = true
versionRange = "${tridot_version_range}"
ordering = "AFTER"
side = "BOTH"
[modproperties.valoria]
    catalogueImageIcon="valoria_icon.png"
    catalogueBackground="valoria_background.png"
    configuredBackground="valoria:textures/block/cut_crystal_stone.png"
